# Generated by Django 2.1 on 2019-09-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autoTradeOnOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_trade_is_on', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auto_trade_on_off',
            },
        ),
        migrations.CreateModel(
            name='batchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batch_record',
            },
        ),
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='conditionOfMA_M5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condition_of_ma',
            },
        ),
        migrations.CreateModel(
            name='conditionOfSlope_M5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condition_of_slope',
            },
        ),
        migrations.CreateModel(
            name='listConditionOfMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'list_condition_of_ma',
            },
        ),
        migrations.CreateModel(
            name='listConditionOfSlope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'list_condition_of_slope',
            },
        ),
        migrations.CreateModel(
            name='M5_USD_JPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('high', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('low', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('close', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('recorded_at_utc', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M5_USD_JPY',
            },
        ),
        migrations.CreateModel(
            name='MA_USD_JPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m5_ma5', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma6', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma10', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma12', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma15', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma20', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma24', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma30', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma36', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma40', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma50', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma70', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma72', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma75', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma140', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma144', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma150', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m5_ma288', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m5', to='auto_trade.M5_USD_JPY')),
            ],
            options={
                'db_table': 'MA_USD_JPY',
            },
        ),
        migrations.CreateModel(
            name='sellBuyAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('position_out', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('position_def', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('is_buy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sell_buy_alert',
            },
        ),
        migrations.CreateModel(
            name='SlopeM5_USD_JPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope_m5_ma5', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma6', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma10', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma12', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma15', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma20', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma24', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma30', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma36', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma40', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma50', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma70', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma72', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma75', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma140', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma144', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma150', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma288', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_leatest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_leatest', to='auto_trade.MA_USD_JPY')),
                ('ma_previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_previous', to='auto_trade.MA_USD_JPY')),
            ],
            options={
                'db_table': 'slope_MA_M5_USD_JPY',
            },
        ),
        migrations.AddField(
            model_name='conditionofslope_m5',
            name='ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma_slope', to='auto_trade.MA_USD_JPY'),
        ),
        migrations.AddField(
            model_name='conditionofslope_m5',
            name='slope_comp5_20_40',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp5_20_40', to='auto_trade.listConditionOfSlope'),
        ),
        migrations.AddField(
            model_name='conditionofslope_m5',
            name='slope_comp5_20_75',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp5_20_75', to='auto_trade.listConditionOfSlope'),
        ),
        migrations.AddField(
            model_name='conditionofslope_m5',
            name='slope_comp6_24_50',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp6_24_50', to='auto_trade.listConditionOfSlope'),
        ),
        migrations.AddField(
            model_name='conditionofslope_m5',
            name='slope_comp6_24_72',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp6_24_72', to='auto_trade.listConditionOfSlope'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma', to='auto_trade.MA_USD_JPY'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp5_20_40',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp5_20_40', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp5_20_75',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp5_20_75', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp6_24_50',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp6_24_50', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp6_24_72',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp6_24_72', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_of_ma_M5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditionOfSlope_M5', to='auto_trade.conditionOfMA_M5'),
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_of_slope_M5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditionOfSlope_M5', to='auto_trade.conditionOfSlope_M5'),
        ),
        migrations.AddField(
            model_name='condition',
            name='ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma', to='auto_trade.MA_USD_JPY'),
        ),
    ]
