# Generated by Django 2.1 on 2019-09-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellbuyalert',
            name='updated_att',
        ),
    ]
