# Generated by Django 2.1 on 2019-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0002_remove_sellbuyalert_updated_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbuyalert',
            name='updated_atww',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
