# Generated by Django 2.1 on 2019-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0002_batchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrecord',
            name='auto_trade_is_on',
            field=models.CharField(default='', max_length=256),
        ),
    ]
