# Generated by Django 2.1 on 2019-09-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0003_batchrecord_auto_trade_is_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchrecord',
            old_name='auto_trade_is_on',
            new_name='text',
        ),
    ]
