# Generated by Django 2.1 on 2019-09-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0006_auto_20190910_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M5',
            new_name='M5_USD_JPY',
        ),
        migrations.RenameModel(
            old_name='MA_USD',
            new_name='MA_USD_JPY',
        ),
        migrations.AlterModelTable(
            name='m5_usd_jpy',
            table='M5_USD_JPY',
        ),
        migrations.AlterModelTable(
            name='ma_usd_jpy',
            table='MA_USD_JPY',
        ),
    ]
