# Generated by Django 2.1 on 2019-09-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0007_auto_20190911_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m5_usd_jpy',
            old_name='record_time',
            new_name='recorded_at_utc',
        ),
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5_ma288',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
