# Generated by Django 2.1 on 2019-09-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0008_auto_20190912_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5_ma12',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5_ma144',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5_ma24',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5_ma36',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5_ma6',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5_ma72',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
