# Generated by Django 2.1 on 2019-09-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0009_auto_20190913_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='conditionOfMA_M5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_trade.MA_USD_JPY')),
            ],
            options={
                'db_table': 'condition_of_ma',
            },
        ),
        migrations.CreateModel(
            name='listConditionOfMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'list_condition_of_ma',
            },
        ),
        migrations.CreateModel(
            name='listConditionOfSlope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'list_condition_of_slope',
            },
        ),
        migrations.CreateModel(
            name='SlopeM5_USD_JPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope_m5_ma5', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma6', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma10', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma12', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma15', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma20', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma24', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma30', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma36', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma40', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma50', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma70', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma72', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma75', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma140', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma144', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma150', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('slope_m5_ma288', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_trade.MA_USD_JPY')),
            ],
            options={
                'db_table': 'slope_MA_M5_USD_JPY',
            },
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp6_24_72',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='slope_comp6_24_72',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_trade.listConditionOfSlope'),
        ),
    ]
