# Generated by Django 2.1 on 2019-09-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0010_auto_20190914_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp5_20_75',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp5_20_75', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='slope_comp5_20_75',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp5_20_75', to='auto_trade.listConditionOfSlope'),
        ),
        migrations.AddField(
            model_name='slopem5_usd_jpy',
            name='ma_leatest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_leatest', to='auto_trade.MA_USD_JPY'),
        ),
        migrations.AlterField(
            model_name='conditionofma_m5',
            name='ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma', to='auto_trade.MA_USD_JPY'),
        ),
        migrations.AlterField(
            model_name='conditionofma_m5',
            name='ma_comp6_24_72',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp6_24_72', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AlterField(
            model_name='conditionofma_m5',
            name='slope_comp6_24_72',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp6_24_72', to='auto_trade.listConditionOfSlope'),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='ma_previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_previous', to='auto_trade.MA_USD_JPY'),
        ),
    ]
