# Generated by Django 2.1 on 2019-09-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0011_auto_20190915_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_usd_jpy',
            name='m5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m5', to='auto_trade.M5_USD_JPY'),
        ),
    ]
