# Generated by Django 2.1 on 2019-09-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0012_ma_usd_jpy_m5'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp5_20_40',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp5_20_40', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp6_24_50',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp6_24_50', to='auto_trade.listConditionOfMA'),
        ),
    ]
