# Generated by Django 2.1 on 2019-09-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0013_auto_20190917_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='conditionOfSlope_M5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma_slope', to='auto_trade.MA_USD_JPY')),
                ('slope_comp5_20_40', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp5_20_40', to='auto_trade.listConditionOfSlope')),
                ('slope_comp5_20_75', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp5_20_75', to='auto_trade.listConditionOfSlope')),
                ('slope_comp6_24_50', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp6_24_50', to='auto_trade.listConditionOfSlope')),
                ('slope_comp6_24_72', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp6_24_72', to='auto_trade.listConditionOfSlope')),
            ],
            options={
                'db_table': 'condition_of_slope',
            },
        ),
        migrations.RemoveField(
            model_name='conditionofma_m5',
            name='slope_comp5_20_75',
        ),
        migrations.RemoveField(
            model_name='conditionofma_m5',
            name='slope_comp6_24_72',
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_of_ma_M5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditionOfSlope_M5', to='auto_trade.conditionOfMA_M5'),
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_of_slope_M5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditionOfSlope_M5', to='auto_trade.conditionOfSlope_M5'),
        ),
        migrations.AddField(
            model_name='condition',
            name='ma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma', to='auto_trade.MA_USD_JPY'),
        ),
    ]
