# Generated by Django 2.1 on 2019-09-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0016_sellbuyalert_updated_att'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sellBuyAlert',
        ),
    ]
