# Generated by Django 2.1 on 2019-09-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0017_delete_sellbuyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellBuyAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('position_out', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('position_def', models.DecimalField(decimal_places=15, default=0.0, max_digits=17)),
                ('is_buy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sell_buy_alert',
            },
        ),
    ]
