# Generated by Django 2.1 on 2019-09-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0018_sellbuyalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sellBuyAlert',
        ),
    ]
