# Generated by Django 2.1 on 2019-09-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0020_sellbuyalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='ma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma', to='auto_trade.MA_USD_JPY'),
        ),
    ]
