# Generated by Django 2.1 on 2019-09-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0022_auto_20190922_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='conditiond',
        ),
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp5_20_75',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp5_20_75', to='auto_trade.listConditionOfMA'),
        ),
    ]
