# Generated by Django 2.1 on 2019-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0023_auto_20190922_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_order', models.IntegerField(default=0)),
                ('long_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
    ]
