# Generated by Django 2.1 on 2019-09-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0024_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp1_6_24',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp1_6_24', to='auto_trade.listConditionOfMA'),
        ),
        migrations.AddField(
            model_name='conditionofslope_m5',
            name='slope_comp1_6_24',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slope_comp1_6_24', to='auto_trade.listConditionOfSlope'),
        ),
    ]
