# Generated by Django 2.1 on 2019-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0025_auto_20190925_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbuyalert',
            name='position_def',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma10',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma12',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma140',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma144',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma15',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma150',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma20',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma24',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma288',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma30',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma36',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma40',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma5',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma50',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma6',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma70',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma72',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='slopem5_usd_jpy',
            name='slope_m5_ma75',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
