# Generated by Django 2.1 on 2019-09-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0026_auto_20190926_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='bollingerBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sma_D20', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('abs_sigma_1', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('abs_sigma_2', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('abs_sigma_3', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bollinger_band',
            },
        ),
    ]
