# Generated by Django 2.1 on 2019-09-27 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0027_bollingerband'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerband',
            name='recorded_at_utc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
