# Generated by Django 2.1 on 2019-09-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0028_bollingerband_recorded_at_utc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bollingerband',
            old_name='sma_D20',
            new_name='sma_M50',
        ),
    ]
