# Generated by Django 2.1 on 2019-09-28 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0029_auto_20190927_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='conditionOfBB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sma_M50', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('abs_sigma_1', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('abs_sigma_2', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('abs_sigma_3', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('recorded_at_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condition_of_bb',
            },
        ),
        migrations.CreateModel(
            name='listConditionOfBBTrande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'list_condition_of_BB_trande',
            },
        ),
    ]
