# Generated by Django 2.1 on 2019-09-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0030_conditionofbb_listconditionofbbtrande'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_of_bb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_of_bb', to='auto_trade.conditionOfBB'),
        ),
    ]
