# Generated by Django 2.1 on 2019-09-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0031_condition_condition_of_bb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionofbb',
            name='abs_sigma_1',
        ),
        migrations.RemoveField(
            model_name='conditionofbb',
            name='recorded_at_utc',
        ),
        migrations.RemoveField(
            model_name='conditionofbb',
            name='sma_M50',
        ),
        migrations.AddField(
            model_name='conditionofbb',
            name='bb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb', to='auto_trade.bollingerBand'),
        ),
        migrations.AddField(
            model_name='conditionofbb',
            name='bb_trande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_trande', to='auto_trade.listConditionOfBBTrande'),
        ),
        migrations.AddField(
            model_name='conditionofbb',
            name='is_shortIn',
            field=models.BooleanField(null=True),
        ),
    ]
