# Generated by Django 2.1 on 2019-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0032_auto_20190928_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionofbb',
            name='abs_sigma_2',
        ),
        migrations.RemoveField(
            model_name='conditionofbb',
            name='abs_sigma_3',
        ),
        migrations.AlterField(
            model_name='bollingerband',
            name='abs_sigma_1',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bollingerband',
            name='abs_sigma_2',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bollingerband',
            name='abs_sigma_3',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bollingerband',
            name='sma_M50',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
    ]
