# Generated by Django 2.1 on 2019-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0033_auto_20190928_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='is_bottomTouch',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='conditionofbb',
            name='is_expansion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='conditionofbb',
            name='is_topTouch',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
