# Generated by Django 2.1 on 2019-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0034_auto_20191002_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionofbb',
            name='is_expansion',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
