# Generated by Django 2.1 on 2019-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0036_batchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='is_expansionByStd',
            field=models.BooleanField(null=True),
        ),
    ]
