# Generated by Django 2.1 on 2019-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0037_conditionofbb_is_expansionbystd'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='is_expansionByNum',
            field=models.BooleanField(null=True),
        ),
    ]
