# Generated by Django 2.1 on 2019-10-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0038_conditionofbb_is_expansionbynum'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='is_longClose',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='conditionofbb',
            name='is_shortClose',
            field=models.BooleanField(null=True),
        ),
    ]
