# Generated by Django 2.1 on 2019-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0039_auto_20191011_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlog',
            name='text',
            field=models.CharField(max_length=2500),
        ),
    ]
