# Generated by Django 2.1 on 2019-10-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0040_auto_20191012_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.IntegerField(default=100)),
                ('text', models.CharField(max_length=2500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
