# Generated by Django 2.1 on 2019-10-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0041_tradesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradesettings',
            old_name='lot',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='tradesettings',
            name='text',
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='on_unit_trade',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='practiceId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='practiceToken',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='realId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='realToken',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='revelage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='use_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
