# Generated by Django 2.1 on 2019-10-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0042_auto_20191013_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradesettings',
            old_name='unit',
            new_name='units',
        ),
    ]
