# Generated by Django 2.1 on 2019-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0043_auto_20191013_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='on_real_trade',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
