# Generated by Django 2.1 on 2019-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0045_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='is_high_sma',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
