# Generated by Django 2.1 on 2019-10-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0047_auto_20191015_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='is_peak',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
