# Generated by Django 2.1 on 2019-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0049_bollingerband_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bollingerband',
            name='cv',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=8, null=True),
        ),
    ]
