# Generated by Django 2.1 on 2019-10-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0050_auto_20191019_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='bb_count',
            field=models.IntegerField(default=50),
        ),
    ]
