# Generated by Django 2.1 on 2019-10-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0051_tradesettings_bb_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='bb_cv_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='bb_slope_dir_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tradesettings',
            name='bb_count',
            field=models.IntegerField(default=15),
        ),
    ]
