# Generated by Django 2.1 on 2019-10-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0052_auto_20191019_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='sig1_adj',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='sig1_adj_exit',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='sig2_adj',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='sig2_adj_exit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='sig3_adj',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='sig3_adj_exit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
