# Generated by Django 2.1 on 2019-10-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0053_auto_20191019_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='slope_001',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conditionofbb',
            name='slope_01',
            field=models.IntegerField(default=0),
        ),
    ]
