# Generated by Django 2.1 on 2019-10-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0054_auto_20191019_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofma_m5',
            name='ma_comp24_75_288',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_comp24_74_288', to='auto_trade.listConditionOfMA'),
        ),
    ]
