# Generated by Django 2.1 on 2019-10-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0058_auto_20191021_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionofbb',
            name='is_longIn',
            field=models.BooleanField(null=True),
        ),
    ]
