# Generated by Django 2.1 on 2019-10-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0059_conditionofbb_is_longin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerband',
            name='abs_sigma_1_2',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bollingerband',
            name='abs_sigma_2_2',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bollingerband',
            name='abs_sigma_3_2',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bollingerband',
            name='sma_2',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
    ]
