# Generated by Django 2.1 on 2019-10-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0060_auto_20191022_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='bb_count_2',
            field=models.IntegerField(default=100),
        ),
    ]
