# Generated by Django 2.1 on 2019-10-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0061_tradesettings_bb_count_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollingerband',
            name='sma_3',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
    ]
