# Generated by Django 2.1 on 2019-10-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0062_bollingerband_sma_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bollingerband',
            old_name='sma_3',
            new_name='sma_M50',
        ),
    ]
