# Generated by Django 2.1 on 2019-10-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0063_auto_20191022_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bollingerband',
            name='sma',
        ),
    ]
