# Generated by Django 2.1 on 2019-10-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0067_auto_20191022_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bollingerband',
            name='sma_4',
        ),
    ]
