# Generated by Django 2.1 on 2019-10-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0069_bollingerband_sma_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bollingerband',
            name='sma_3',
        ),
    ]
