# Generated by Django 2.1 on 2019-10-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0070_remove_bollingerband_sma_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='limit',
            field=models.DecimalField(decimal_places=8, default=0.0002, max_digits=9),
        ),
    ]
