# Generated by Django 2.1 on 2019-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0071_tradesettings_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_count', models.IntegerField(default=15)),
                ('long_count', models.IntegerField(default=15)),
                ('is_short_lock', models.BooleanField(default=False)),
                ('is_long_lock', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
