# Generated by Django 2.1 on 2019-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0072_tradelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='long_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='short_count',
            field=models.IntegerField(default=0),
        ),
    ]
