# Generated by Django 2.1 on 2019-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0073_auto_20191025_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='long_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='short_in_time',
            field=models.DateTimeField(null=True),
        ),
    ]
