# Generated by Django 2.1 on 2019-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0074_auto_20191030_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='wait_time',
            field=models.IntegerField(default=10),
        ),
    ]
