# Generated by Django 2.1 on 2019-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0075_tradesettings_wait_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='use_specific_limit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
