# Generated by Django 2.1 on 2019-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0076_tradesettings_use_specific_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlog',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
