# Generated by Django 2.1 on 2019-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0077_auto_20191114_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='condition_id',
            field=models.IntegerField(default=0),
        ),
    ]
