# Generated by Django 2.1 on 2019-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0078_tradelog_condition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='ma_in_at',
            field=models.DateTimeField(null=True),
        ),
    ]
