# Generated by Django 2.1 on 2019-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0079_tradelog_ma_in_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='specifcCandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('high', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('low', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('close', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('recorded_at_utc', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'specifc_candle',
            },
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='granularity',
            field=models.CharField(default='M1', max_length=100),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='instruments',
            field=models.CharField(default='USD_JPY', max_length=100),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='long_leg',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='middle_leg',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradesettings',
            name='short_leg',
            field=models.IntegerField(default=1),
        ),
    ]
