# Generated by Django 2.1 on 2019-11-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0080_auto_20191125_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='MA_Specific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_short', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m_middle', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('m_long', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m', to='auto_trade.specifcCandle')),
            ],
            options={
                'db_table': 'MA_specific',
            },
        ),
        migrations.CreateModel(
            name='SlopeMA_specific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope_short_specific', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('slope_middle_specific', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('slope_long_specific', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_leatest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_leatest', to='auto_trade.MA_Specific')),
                ('ma_previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_previous', to='auto_trade.MA_Specific')),
            ],
            options={
                'db_table': 'slope_MA_specific',
            },
        ),
    ]
