# Generated by Django 2.1 on 2019-11-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0082_auto_20191125_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma_specific',
            name='ms_long',
        ),
    ]
