# Generated by Django 2.1 on 2019-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0083_remove_ma_specific_ms_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_specific',
            name='ema_long',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='ema_middle',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='ema_short',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tradesettings',
            name='long_leg',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='tradesettings',
            name='middle_leg',
            field=models.IntegerField(default=20),
        ),
    ]
