# Generated by Django 2.1 on 2019-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0085_auto_20191125_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_specific',
            name='macd1',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='macd2',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='macd3',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
