# Generated by Django 2.1 on 2019-11-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0086_auto_20191126_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_specific',
            name='compMa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='compSlope',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='past_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_m', to='auto_trade.specificCandle'),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='slopeDir',
            field=models.IntegerField(default=0),
        ),
    ]
