# Generated by Django 2.1 on 2019-11-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0087_auto_20191126_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ma_specific',
            old_name='compSlope',
            new_name='compMaSlope',
        ),
    ]
