# Generated by Django 2.1 on 2019-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0088_auto_20191128_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_specific',
            name='compEma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='compEmaSlope',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='compMacd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ma_specific',
            name='compMacdSlope',
            field=models.IntegerField(default=0),
        ),
    ]
