# Generated by Django 2.1 on 2019-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0089_auto_20191128_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='use_cnt',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
