# Generated by Django 2.1 on 2019-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0090_tradesettings_use_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='use_trailing_stop',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
