# Generated by Django 2.1 on 2019-12-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0092_auto_20191210_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_of_bb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_of_bb', to='auto_trade.conditionOfBB'),
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_of_ma_M5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditionOfSlope_M5', to='auto_trade.conditionOfMA_M5'),
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_of_slope_M5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditionOfSlope_M5', to='auto_trade.conditionOfSlope_M5'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='ma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma', to='auto_trade.MA_USD_JPY'),
        ),
    ]
