# Generated by Django 2.1 on 2019-12-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0093_auto_20191210_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='condition_of_bb',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='condition_of_ma_M5',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='condition_of_slope_M5',
        ),
    ]
