# Generated by Django 2.1 on 2019-12-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0095_auto_20191210_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='mas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma', to='auto_trade.MA_Specific'),
        ),
    ]
