# Generated by Django 2.1 on 2019-12-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0099_condition_condition_of_slope_m5ssss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='condition_of_slope_M5ssss',
        ),
    ]
