# Generated by Django 2.1 on 2019-12-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0102_auto_20191210_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='ma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma', to='auto_trade.MA_USD_JPY'),
        ),
        migrations.AddField(
            model_name='condition',
            name='mas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma2', to='auto_trade.MA_Specific'),
        ),
        migrations.AddField(
            model_name='condition',
            name='mas2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma3', to='auto_trade.MA_Specific'),
        ),
    ]
