# Generated by Django 2.1 on 2019-12-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0103_auto_20191210_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='ma',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='mas',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='mas2',
        ),
    ]
