# Generated by Django 2.1 on 2019-12-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0104_auto_20191210_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='maqq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma', to='auto_trade.MA_USD_JPY'),
        ),
        migrations.AddField(
            model_name='condition',
            name='mas2qq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma3', to='auto_trade.MA_Specific'),
        ),
        migrations.AddField(
            model_name='condition',
            name='masqq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma2', to='auto_trade.MA_Specific'),
        ),
    ]
