# Generated by Django 2.1 on 2019-12-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0105_auto_20191210_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='maqq',
            new_name='ma',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='masqq',
            new_name='mas',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='mas2qq',
            new_name='mas2',
        ),
    ]
