# Generated by Django 2.1 on 2019-12-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0108_auto_20191210_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='mas2',
        ),
    ]
