# Generated by Django 2.1 on 2019-12-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0109_remove_condition_mas2'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='maqq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma2', to='auto_trade.MA_USD_JPY'),
        ),
        migrations.AddField(
            model_name='condition',
            name='mas2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma3', to='auto_trade.MA_Specific'),
        ),
        migrations.AddField(
            model_name='condition',
            name='mas2qq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma4', to='auto_trade.MA_Specific'),
        ),
    ]
