# Generated by Django 2.1 on 2019-12-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0110_auto_20191210_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='mas2',
        ),
        migrations.AddField(
            model_name='condition',
            name='masqq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_ma3', to='auto_trade.MA_Specific'),
        ),
    ]
