# Generated by Django 2.1 on 2019-12-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0111_auto_20191210_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='maqq',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='mas2qq',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='masqq',
        ),
    ]
