# Generated by Django 2.1 on 2019-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0112_auto_20191210_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='use_specific_unit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
