# Generated by Django 2.1 on 2019-12-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0113_tradesettings_use_specific_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesettings',
            name='on_unit_trade',
        ),
        migrations.RemoveField(
            model_name='tradesettings',
            name='use_amount',
        ),
    ]
