# Generated by Django 2.1 on 2019-12-14 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0114_auto_20191214_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesettings',
            name='revelage',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
