# Generated by Django 2.1 on 2019-12-14 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0115_auto_20191214_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesettings',
            name='usage_rates',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
